# Generated by Django 3.2.9 on 2021-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0003_alter_chairmodel_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmodel',
            name='ubicacion',
            field=models.CharField(default='Estacion de carga', max_length=255),
        ),
    ]
