# Generated by Django 3.2.9 on 2021-11-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0004_alter_chairmodel_ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartamentoModel',
        ),
    ]
